name: Brian Guay
favicon: null
layout_spectrum: 0.1822902993299067
typography_spectrum: 0.5436061373911798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05646883579902351
  lightness: 0.07863606698811054
  saturation: 0.6881212370935827
  rhythmicContrast: 0.651271776529029
purpose: []
